version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: back-end-nest
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - nest-react-mysql-network
    ports:
      - "3003:3003"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0835897600Za
      POSTGRES_DB: back_end_db
    depends_on:
      - postgres
    command: >
      sh -c "npm install && npm run start:dev --watch"

  postgres:
    image: postgres
    container_name: back-end-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0835897600Za
      POSTGRES_DB: back_end_db
    ports:
      - "5433:5432"
    volumes:
      - mysql-data:/var/lib/postgresql/data
    networks:
      - nest-react-mysql-network

#Docker Networks
networks:
  nest-react-mysql-network:
    driver: bridge

#Docker Volumes
volumes:
  mysql-data:
    driver: local
